### ISSUE TITLE
error when building new lock/examples/bundling/webpack/

### ISSUE THREAD

**Issue by Tarostar** [auth0/lock#1144]
When doing npm run build with the new webpack example I get the error:
`error auth0-lock-webpack@0.0.0 build: cross-env NODE_ENV=production webpack -p`

npm 3.10.10 running in Git Bash on Windows 10.
node v6.11.3

npm-debug.log reports:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle auth0-lock-webpack@0.0.0~prebuild: auth0-lock-webpack@0.0.0
6 silly lifecycle auth0-lock-webpack@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle auth0-lock-webpack@0.0.0~build: auth0-lock-webpack@0.0.0
8 verbose lifecycle auth0-lock-webpack@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle auth0-lock-webpack@0.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Utvikling\Samples\lock\examples\bundling\webpack\node_modules\.bin;C:\Users\Claus\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Claus\bin;C:\Python27;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\OpenVPN\bin;C:\Users\Claus\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Utvikling\ECE5.6\apache-tomcat-7.0.42;C:\Program Files\Java\jre1.8.0_45;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Git\cmd;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\dotnet;C:\Program Files (x86)\Skype\Phone;C:\Program Files\nodejs;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Oracle\VirtualBox;C:\Users\Claus\AppData\Local\Microsoft\WindowsApps;C:\Users\Claus\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle auth0-lock-webpack@0.0.0~build: CWD: C:\Utvikling\Samples\lock\examples\bundling\webpack
11 silly lifecycle auth0-lock-webpack@0.0.0~build: Args: [ '/d /s /c', 'cross-env NODE_ENV=production webpack -p' ]
12 silly lifecycle auth0-lock-webpack@0.0.0~build: Returned: code: 1  signal: null
13 info lifecycle auth0-lock-webpack@0.0.0~build: Failed to exec build script
14 verbose stack Error: auth0-lock-webpack@0.0.0 build: `cross-env NODE_ENV=production webpack -p`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid auth0-lock-webpack@0.0.0
16 verbose cwd C:\Utvikling\Samples\lock\examples\bundling\webpack
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.11.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error auth0-lock-webpack@0.0.0 build: `cross-env NODE_ENV=production webpack -p`
22 error Exit status 1
23 error Failed at the auth0-lock-webpack@0.0.0 build script 'cross-env NODE_ENV=production webpack -p'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the auth0-lock-webpack package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env NODE_ENV=production webpack -p
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs auth0-lock-webpack
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls auth0-lock-webpack
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Tarostar** [comment]
Note, if I change package.json to just do: `"build": "webpack" `it does build, but when I open index.html I get the error: 

> Uncaught SyntaxError: Unexpected token import build.js 47

This line: `import Auth0Lock from 'auth0-lock';`

**Comment by Tarostar** [comment]
Never mind, all is well and this issue can be deleted/closed. I simply forgot to update the packages with npm install (I had done an npm install prior to the latest changes, but obviously that is not enough).

**Comment by Tarostar** [comment]
Never mind, all is well and this issue can be deleted/closed. I simply forgot to update the packages with npm install (I had done an npm install prior to the latest changes, but obviously that is not enough).
