### ISSUE TITLE
'forEach' of undefined : After login the auth0 lock emits an error

### ISSUE THREAD

**Issue by vincentdesmares** [auth0/lock#1599]
### Description

After login the auth0 lock emits an error.

```
TypeError: Cannot read property 'forEach' of undefined
  at execCallbacks(../node_modules/auth0-lock/lib/utils/cache.js:53:1)
  at cb(../node_modules/auth0-lock/lib/utils/cache.js:38:1)
  at cb(../node_modules/auth0-js/dist/auth0.min.esm.js:4160:6)
  at callback(../node_modules/auth0-js/dist/auth0.min.esm.js:3706:1)
  at cb(../node_modules/auth0-js/dist/auth0.min.esm.js:3724:1)
  at fn(../node_modules/auth0-js/dist/auth0.min.esm.js:1383:6)
  at callback(../node_modules/auth0-js/dist/auth0.min.esm.js:755:1)
  at apply(../node_modules/auth0-js/dist/auth0.min.esm.js:696:1)
  at emit(../node_modules/auth0-js/dist/auth0.min.esm.js:311:1)
  at apply(../node_modules/auth0-js/dist/auth0.min.esm.js:788:1)
  at XMLHttpRequest.o(../node_modules/raven-js/src/raven.js:363:1)
```
### Environment

Please provide the following:

* Lock version: 11.10.0
* Browser version: Chrome 49.0.2623
* OS: Windows XP

### Reproduction

I could not reproduce it.

Here is one detail that might help, the error happened just after a GET for https://xxx.auth0.com/userinfo that returned successfully [200].

**Comment by luisrudge** [comment]
do you have a code snippet or something? did you try with latest lock? without a repro it's unlikely we'll find the issue.

**Comment by kheyse-oqton** [comment]
Unfortunately this seems to be a common error for us too.
It's seemingly random, and we have not found a pattern yet.
