### ISSUE TITLE
 SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by dgilling** [auth0/lock#1795]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Upgrade 11.18.1 to 11.21.0 and get following error on build:
This is a Node + React app with Server Side Rendering.

0] Module build failed (from ./node_modules/transform-loader/cacheable.js):
[0] SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (8:147323)
[0]     at Parser.pp$4.raise (gcnode_modules/acorn/dist/acorn.js:2757:13)
[0]     at Parser.pp$1.parseStatement (gcnode_modules/acorn/dist/acorn.js:799:16)
[0]     at Parser.pp$1.parseTopLevel (gcnode_modules/acorn/dist/acorn.js:706:23)
[0]     at Parser.parse (gcnode_modules/acorn/dist/acorn.js:551:15)
[0]     at parse (gcnode_modules/acorn/dist/acorn.js:5288:37)
[0]     at module.exports (gcnode_modules/falafel/index.js:22:15)
[0]     at gcnode_modules/static-module/index.js:57:13
[0]     at ConcatStream.<anonymous> (gcnode_modules/concat-stream/index.js:37:43)
[0]     at ConcatStream.emit (events.js:203:15)
[0]     at finishMaybe (gcnode_modules/readable-stream/lib/_stream_writable.js:630:14)
[0]  @ ./node_modules/auth0-lock/lib/utils/cdn_utils.js 7:15-34
[0]  @ ./node_modules/auth0-lock/lib/i18n.js
[0]  @ ./node_modules/auth0-lock/lib/engine/classic/login.js
[0]  @ ./node_modules/auth0-lock/lib/engine/classic.js
[0]  @ ./node_modules/auth0-lock/lib/lock.js
[0]  @ ./node_modules/auth0-lock/lib/index.js
> Provide a clear and concise description of the issue, including what you expected to happen.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of this library used:** Node 10
- **Version of the platform or framework used, if applicable:** Express
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
@dgilling I'm unsure based off the issue report. Do you have a small repro you can share so that we can take a closer look?

**Comment by stevehobbsdev** [comment]
Closing as I'm unable to reproduced based off the issue report.
