### ISSUE TITLE
Passwordless SMS country code

### ISSUE THREAD

**Issue by spenthil** [auth0/lock#2008]
### Describe the problem

When I click on the country code button for a passwordless sms login the model turns grey with the following error in console:

```
react_devtools_backend.js:13444 Uncaught Invariant Violation: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r (https://cdn.auth0.com/js/lock/11.30/lock.min.js:9:19827)
    at i (https://cdn.auth0.com/js/lock/11.30/lock.min.js:9:590814)
    at r (https://cdn.auth0.com/js/lock/11.30/lock.min.js:9:798498)
    at o (https://cdn.auth0.com/js/lock/11.30/lock.min.js:9:592173)
    at o (https://cdn.auth0.com/js/lock/11.30/lock.min.js:9:592295)
    at i (https://cdn.auth0.com/js/lock/11.30/lock.min.js:9:592705)
    at Object.instantiateChildren (https://cdn.auth0.com/js/lock/11.30/lock.min.js:9:798683)
    at g._reconcilerInstantiateChildren (https://cdn.auth0.com/js/lock/11.30/lock.min.js:9:831857)
    at g.mountChildren (https://cdn.auth0.com/js/lock/11.30/lock.min.js:9:832064)
    at g._createInitialChildren (https://cdn.auth0.com/js/lock/11.30/lock.min.js:9:814798)
```

### What was the expected behavior?

A selector for country code.

### Reproduction

- Step 1..
- Step 2..
- ...

### Environment

- **Version of this library used:** 11.30
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by spenthil** [comment]
When using non-minified:
```
react_devtools_backend.js:13444 Uncaught Invariant Violation: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (https://cdn.auth0.com/js/lock/11.30/lock.js:1342:15)
    at instantiateReactComponent (https://cdn.auth0.com/js/lock/11.30/lock.js:23709:218)
    at instantiateChild (https://cdn.auth0.com/js/lock/11.30/lock.js:38848:28)
    at traverseAllChildrenImpl (https://cdn.auth0.com/js/lock/11.30/lock.js:23953:5)
    at traverseAllChildrenImpl (https://cdn.auth0.com/js/lock/11.30/lock.js:23969:23)
    at traverseAllChildren (https://cdn.auth0.com/js/lock/11.30/lock.js:24048:10)
    at Object.instantiateChildren (https://cdn.auth0.com/js/lock/11.30/lock.js:38878:7)
    at ReactDOMComponent._reconcilerInstantiateChildren (https://cdn.auth0.com/js/lock/11.30/lock.js:42937:35)
    at ReactDOMComponent.mountChildren (https://cdn.auth0.com/js/lock/11.30/lock.js:42970:27)
    at ReactDOMComponent._createInitialChildren (https://cdn.auth0.com/js/lock/11.30/lock.js:40712:32)
```

**Comment by spenthil** [comment]
Works fine with 11.29.
