### ISSUE TITLE
Text selection on login screen results in application crash

### ISSUE THREAD

**Issue by nitzanma** [auth0/lock#2046]
Hi, 
We're using your login widget, in a web app that is shown as a WebView object as part of a mobile app.
(for more info on Webviews:  https://searchsecurity.techtarget.com/definition/Android-Webview)

On all android versions, we view this issue:
Steps to reproduce:
1. During login, while in phone number screen
2. Long press on the phone number field or long press on any text marked in the red square

![image](https://user-images.githubusercontent.com/48408041/135236988-cea5574a-72b8-43db-af78-46af423b5aff.png)

Actual result:
App crashes

with see this exception:
Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x20c0016
at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:239)
at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96)
at android.content.res.Resources.getInteger(Resources.java:1129)
at org.chromium.ui.base.DeviceFormFactor.b(chromium-TrichromeWebViewGoogle6432.aab-stable-457708234:4)
at org.chromium.content.browser.selection.SelectionPopupControllerImpl.m(chromium-TrichromeWebViewGoogle6432.aab-stable-457708234:1)
at u8.onCreateActionMode(chromium-TrichromeWebViewGoogle6432.aab-stable-457708234:8)
at Pw.onCreateActionMode(chromium-TrichromeWebViewGoogle6432.aab-stable-457708234:2)
at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onCreateActionMode(DecorView.java:2644)
at com.android.internal.policy.DecorView.startActionMode(DecorView.java:937)
at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:893)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1017)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1017)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1017)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1017)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1017)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1017)
at android.view.View.startActionMode(View.java:7359)
at org.chromium.content.browser.selection.SelectionPopupControllerImpl.H(chromium-TrichromeWebViewGoogle6432.aab-stable-457708234:10)
at Rg0.a(chromium-TrichromeWebViewGoogle6432.aab-stable-457708234:10)
at Wj0.i(chromium-TrichromeWebViewGoogle6432.aab-stable-457708234:4)
at h6.run(chromium-TrichromeWebViewGoogle6432.aab-stable-457708234:3)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:224)
at android.app.ActivityThread.main(ActivityThread.java:7520)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

is this familiar to you? couldn't find anything in the issues section.
Will appreciate your help.
Thanks!

**Comment by stevehobbsdev** [comment]
I'm afraid this isn't a familiar issue, no, and I'm not sure what to suggest. If you're able to supply a reproduction app that I can run and test, I can take a look.

**Comment by nitzanma** [comment]
> I'm afraid this isn't a familiar issue, no, and I'm not sure what to suggest. If you're able to supply a reproduction app that I can run and test, I can take a look.

Hi,
Thanks for your response.
You may download the app from google play:
https://play.google.com/store/apps/details?id=com.tg17.ud&hl=en&gl=US

**Comment by stevehobbsdev** [comment]
@nitzanma just to confirm, are you using this SDK for Lock.js, or are you using [Lock.Android](https://github.com/auth0/Lock.Android/)?

This SDK is for JavaScript applications, we don't do anything to handle long press or anything of that nature. Just wondering if this issue has been raised in the right place.

**Comment by nitzanma** [comment]
@stevehobbsdev  correct.
inside the app, when you reach the login page - this is a js web application that is loaded via WebView.

**Comment by stevehobbsdev** [comment]
@nitzanma Thanks for that context.

Thanks for pointing me to the Play Store earlier to get your app. What I'll need in order to reproduce this is a sample that I can run locally in an emulator rather than a finished app. From the stack trace you posted it looks as though something is happening outside the bounds of the SDK itself. Not being a native SDK, we of course can't interact ourselves with the native Android API, so as it is at the moment, it's difficult to pinpoint where or indeed if the SDK is causing a problem.

If you can provide me with a small reproducible sample app that demonstrates the issue, I can have a look.
