### ISSUE TITLE
Don't break server-side rendering

### ISSUE THREAD

**Issue by rkoberg** [auth0/lock#592]
Even if it is a client-side library, do not break server-side render. As it is now, just importing the library will break the server-side in an isomorphic app.

**Comment by danreeves** [comment]
Was this fixed in #631?

**Comment by shankiesan** [comment]
As far as I can tell, it's not working on 10.10.2

**Comment by shankiesan** [comment]
Ah my bad, looks like the PR hasn't been merged yet so it hasn't been pushed to NPM. I'll try pulling directly from GitHub and report back...

**Comment by hzalaz** [comment]
Some changes were made in lock.js and auth0.js to avoid relying on window object and breaking server side rendering but lock is not there yet (auth0.js v8 can be used without issues)

**Comment by camsjams** [comment]
Also seems to be an issue inside the `url_utils` file:

```
/var/www/node_modules/auth0-lock/lib/utils/url_utils.js:6
 var parser = global.document.createElement("a");
                             ^
 TypeError: Cannot read property 'createElement' of undefined
     at parseUrl (/var/www/node_modules/auth0-lock/lib/utils/url_utils.js:6:31)
     at extractClientBaseUrlOption (/var/www/node_modules/auth0-lock/lib/core/index.js:421:42)
     at Object.setup (/var/www/node_modules/auth0-lock/lib/core/index.js:110:20)
     at setupLock (/var/www/node_modules/auth0-lock/lib/core/actions.js:47:13)
     at Auth0Lock.Base (/var/www/node_modules/auth0-lock/lib/core.js:77:36)
     at new Auth0Lock (/var/www/node_modules/auth0-lock/lib/index.js:49:56)
     at new AuthService (/var/www/build/server.js:4880:15)
     at Object.module.exports.Object.defineProperty.value (/var/www/build/server.js:4812:12)
     at __webpack_require__ (/var/www/build/server.js:21:30)
     at Object.module.exports.Object.defineProperty.value (/var/www/build/server.js:788:15)

```

**Comment by hzalaz** [comment]
We are working on improving the server side support of Lock but we are busy working on other priority changes/fixes that are delaying us.
