### ISSUE TITLE
ENOENT Error after updating auth0-lock to v10

### ISSUE THREAD

**Issue by askamil** [auth0/lock#777]
Few days ago I have updated my auth0-lock from v7 to v10. This is what I got after using `ember server`:
```
kamil@kamil:~/Workspace/surplace-dashboard$ ember server
Livereload server on http://localhost:49152
Serving on http://localhost:4200/dashboard/
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/home/kamil/Workspace/surplace-dashboard/tmp/source_map_concat-input_base_path-zjanmxBB.tmp/0/bower_components/auth0-lock/build/auth0-lock.js'
    at Object.fs.statSync (fs.js:906:18)
    at Concat.keyForFile (/home/kamil/Workspace/surplace-dashboard/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:87:20)
    at Array.map (native)
    at Concat.CachingWriter._conditionalBuild (/home/kamil/Workspace/surplace-dashboard/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:109:65)
    at /home/kamil/Workspace/surplace-dashboard/node_modules/broccoli-concat/node_modules/broccoli-plugin/read_compat.js:61:34
    at tryCatch (/home/kamil/Workspace/surplace-dashboard/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/home/kamil/Workspace/surplace-dashboard/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/home/kamil/Workspace/surplace-dashboard/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/home/kamil/Workspace/surplace-dashboard/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at Concat.Plugin (/home/kamil/Workspace/surplace-dashboard/node_modules/broccoli-concat/node_modules/broccoli-plugin/index.js:10:31)
    at Concat.CachingWriter [as constructor] (/home/kamil/Workspace/surplace-dashboard/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:18:10)
    at new Concat (/home/kamil/Workspace/surplace-dashboard/node_modules/broccoli-concat/concat.js:32:17)
    at module.exports (/home/kamil/Workspace/surplace-dashboard/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/home/kamil/Workspace/surplace-dashboard/node_modules/ember-cli/lib/broccoli/ember-app.js:348:10)
    at EmberApp.javascript (/home/kamil/Workspace/surplace-dashboard/node_modules/ember-cli/lib/broccoli/ember-app.js:1214:12)
    at EmberApp.toArray (/home/kamil/Workspace/surplace-dashboard/node_modules/ember-cli/lib/broccoli/ember-app.js:1566:10)
    at EmberApp.toTree (/home/kamil/Workspace/surplace-dashboard/node_modules/ember-cli/lib/broccoli/ember-app.js:1588:30)
    at module.exports (/home/kamil/Workspace/surplace-dashboard/ember-cli-build.js:89:14)
    at Class.setupBroccoliBuilder (/home/kamil/Workspace/surplace-dashboard/node_modules/ember-cli/lib/models/builder.js:54:19)

```

```
ember-cli: 2.6.2
node: 7.3.0
os: linux x64
npm: 2.15.1

dependencies:
"ember": "~2.6.0",
"auth0-lock": "^10.8.1"

```

**Comment by hzalaz** [comment]
@askamil seems to me that is not a lock issue but an issue with your bundler or how it's configured since it's not finding the file downloaded using bower

**Comment by askamil** [comment]
@hzalaz seems that I fixed it but I have no clue if in proper way. In path' /bower_components/auth0-lock/build' I have file named 'lock.js' so I renamed it to 'auth0-lock.js'. Could I do that? I saw this solution in similar topic.

**Comment by askamil** [comment]
The issue was caused by the conflict with `auth0-ember-simple-auth`.
To fix that you have to add following line
`app.import(app.bowerDirectory + '/auth0-lock/build/lock.js');`
to your `index.js` and `ember-cli-build.js` files of `auth0-ember-simple-auth` repository.
