### ISSUE TITLE
Angular2 "EXCEPTION: Uncaught (in promise): TypeError: Object doesn't support this action" after version upgrade

### ISSUE THREAD

**Issue by gsmyth** [auth0/lock#819]
I've just upgraded my angular2 core versions, and now a previously working auth0 lock setup is now broken. It builds fine, but throws an Exception on the console - "TypeError: Object doesn't support this action"

- [ ] Code snippet or sample project that reproduces the bug

Pretty vanilla lock setup (copied from the setup docs):-

###
  options = {
    theme: {
      labeledSubmitButton: false,
      logo: "assets/logo.png",
      primaryColor: "#ed693d"
    },
    languageDictionary: {
      title: "My Company"
    },
    auth: {
    responseType: 'token',
    redirectUrl: environment.loginRedirectUrl
    }
  };

  lock = new Auth0Lock('BLAHBLAHBLAH', 'ENDPOINT.eu.auth0.com', this.options );
###

Error being thrown on the console is:-
 
Unhandled Promise rejection: Object doesn't support this action ; Zone: angular ; Task: Promise.then ; Value: TypeError: Object doesn't support this action TypeError: Object doesn't support this action
   at Auth0LegacyAPIClient (http://localhost:4200/vendor.bundle.js:117528:5)
   at setupClient (http://localhost:4200/vendor.bundle.js:48844:7)
   at setupLock (http://localhost:4200/vendor.bundle.js:17310:3)
   at Base (http://localhost:4200/vendor.bundle.js:116866:5)
   at Auth0Lock (http://localhost:4200/vendor.bundle.js:88379:5)
   at AuthService (http://localhost:4200/main.bundle.js:674:9)
   at _AuthService_58.get (Function code:390:43)
   at AppModuleInjector.prototype.getInternal (Function code:516:41)
   at NgModuleInjector.prototype.get (http://localhost:4200/vendor.bundle.js:80274:9)
   at AppView.prototype.injectorGet (http://localhost:4200/vendor.bundle.js:109710:17)
   at DebugAppView.prototype.injectorGet (http://localhost:4200/vendor.bundle.js:110138:13)
   at ElementInjector.prototype.get (http://localhost:4200/vendor.bundle.js:109218:9)
   at ReflectiveInjector_.prototype._getByKeyDefault (http://localhost:4200/vendor.bundle.js:108986:13)
   at ReflectiveInjector_.prototype._getByKey (http://localhost:4200/vendor.bundle.js:108939:13)
   at ReflectiveInjector_.prototype.get (http://localhost:4200/vendor.bundle.js:108701:9)
vendor.bundle.js (148851,13)
   "Unhandled Promise rejection:"
   "Object doesn't support this action"
   "; Zone:"
   "angular"
   "; Task:"
   "Promise.then"
   "; Value:"
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support this action",
      message: "Object doesn't support this action",
      name: "TypeError",
      number: -2146827843,
      stack: "TypeError: Object doesn't support this action
   at Auth0LegacyAPIClient (http://localhost:4200/vendor.bundle.js:117528:5)
   at setupClient (http://localhost:4200/vendor.bundle.js:48844:7)
   at setupLock (http://localhost:4200/vendor.bundle.js:17310:3)
   at Base (http://localhost:4200/vendor.bundle.js:116866:5)
   at Auth0Lock (http://localhost:4200/vendor.bundle.js:88379:5)
   at AuthService (http://localhost:4200/main.bundle.js:674:9)
   at _AuthService_58.get (Function code:390:43)
   at AppModuleInjector.prototype.getInternal (Function code:516:41)
   at NgModuleInjector.prototype.get (http://localhost:4200/vendor.bundle.js:80274:9)
   at AppView.prototype.injectorGet (http://localhost:4200/vendor.bundle.js:109710:17)
   at DebugAppView.prototype.injectorGet (http://localhost:4200/vendor.bundle.js:110138:13)
   at ElementInjector.prototype.get (http://localhost:4200/vendor.bundle.js:109218:9)
   at ReflectiveInjector_.prototype._getByKeyDefault (http://localhost:4200/vendor.bundle.js:108986:13)
   at ReflectiveInjector_.prototype._getByKey (http://localhost:4200/vendor.bundle.js:108939:13)
   at ReflectiveInjector_.prototype.get (http://localhost:4200/vendor.bundle.js:108701:9)"
   }
   "TypeError: Object doesn't support this action
   at Auth0LegacyAPIClient (http://localhost:4200/vendor.bundle.js:117528:5)
   at setupClient (http://localhost:4200/vendor.bundle.js:48844:7)
   at setupLock (http://localhost:4200/vendor.bundle.js:17310:3)
   at Base (http://localhost:4200/vendor.bundle.js:116866:5)
   at Auth0Lock (http://localhost:4200/vendor.bundle.js:88379:5)
   at AuthService (http://localhost:4200/main.bundle.js:674:9)
   at _AuthService_58.get (Function code:390:43)
   at AppModuleInjector.prototype.getInternal (Function code:516:41)
   at NgModuleInjector.prototype.get (http://localhost:4200/vendor.bundle.js:80274:9)
   at AppView.prototype.injectorGet (http://localhost:4200/vendor.bundle.js:109710:17)
   at DebugAppView.prototype.injectorGet (http://localhost:4200/vendor.bundle.js:110138:13)
   at ElementInjector.prototype.get (http://localhost:4200/vendor.bundle.js:109218:9)
   at ReflectiveInjector_.prototype._getByKeyDefault (http://localhost:4200/vendor.bundle.js:108986:13)
   at ReflectiveInjector_.prototype._getByKey (http://localhost:4200/vendor.bundle.js:108939:13)
   at ReflectiveInjector_.prototype.get (http://localhost:4200/vendor.bundle.js:108701:9)"

- [ ] Lock version
###
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "angular2-jwt": "^0.1.28",
    "auth0-js": "^7.4.0",
    "auth0-lock": "^10.9.2",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "web-animations-js": "^2.2.2",
    "zone.js": "^0.7.2"
  }
###

- [ ] Browser & OS
Happening in FIrefox(50.1.0) and Edge(38.14393.0.0) on Windows 10 (Version10.0.14393 Build 14393)

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

**Comment by hzalaz** [comment]
@gsmyth the error does not tell a lot. Can you build a sample where we can reproduce this error since you are bundling Lock yourself?

**Comment by glena** [comment]
Also, can you show your unminified bundle around this line `http://localhost:4200/vendor.bundle.js:117528:5` ?

**Comment by glena** [comment]
from what version are you upgrading?

Seems that the issue is related to the version of auth0.js. Lock 10.9+ started using auth0.js v8.

**Comment by gsmyth** [comment]
That seems to have been the issue - I've upgraded auth0-js to "8.0.4" and
all is working again.

Many thanks!
G

**Comment by gsmyth** [comment]
And this was upgrading from:-

    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/router": "3.2.3",
    "angular2-jwt": "^0.1.25",
    "auth0-js": "^7.4.0",
    "auth0-lock": "^10.6.1"

**Comment by glena** [comment]
Cool :)

If you were using auth0.js in your project besides lock, you should have in mind it was a complete rework and the api did change.
