### ISSUE TITLE
Unable to destroy Lock instance

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/lock#907]
Hey guys,

I see this error when I call `lock.destroy()`:

```js
Uncaught TypeError: Cannot read property 'getIn' of undefined
    at http://localhost:3001/assets/vendors.js:16215:15
    at getUIAttribute (http://localhost:3001/assets/vendors.js:7967:10)
    at Object.avatar (http://localhost:3001/assets/vendors.js:7984:12)
    at http://localhost:3001/assets/vendors.js:6961:25
    at Object.render-1 (http://localhost:3001/assets/vendors.js:12553:20)
    at http://localhost:3001/assets/vendors.js:15998:24
    at Array.forEach (native)
    at Atom._change (http://localhost:3001/assets/vendors.js:15997:26)
    at Atom.swap (http://localhost:3001/assets/vendors.js:15969:17)
    at swap (http://localhost:3001/assets/vendors.js:12566:21)
    at removeLock (http://localhost:3001/assets/vendors.js:7289:19)
    at Auth0Lock.destroy (http://localhost:3001/assets/vendors.js:7061:29)
    at Auth0Lock.<anonymous> (http://localhost:3001/assets/client.js:35:12)
    at Auth0Lock../node_modules/events/events.js.EventEmitter.emit (http://localhost:3001/assets/vendors.js:31155:17)
    at http://localhost:3001/assets/vendors.js:8337:35
```

**Comment by luisrudge** [comment]
@sandrinodimattia can you share more about this? what lock version, how are you instantiating lock, how are you calling lock.show()?

**Comment by luisrudge** [comment]
I can repro this. We'll fix this eventually. Since it's not a documented API, I'm assigning this with a low priority

**Comment by iorrah** [comment]
Hey @luisrudg, just landed on this thread from March 2017 and was wondering if this will be tackled any time soon?

**Comment by luisrudge** [comment]
When the component is unmounted, GC will get rid of your internal state, so there's no memory leaks. Yes, we still have to fix this and there's a PR to fix it: https://github.com/auth0/lock/pull/1091 - but this PR touches in a crucial part of the widget and I didn't have time to test all features of lock to make sure everything works.

**Comment by jkhlim** [comment]
Just want to add a +1 to this feature.

**Comment by luisrudge** [comment]
dupe #1090
